### ISSUE TITLE
name 'batchnormsync' is not defined

### ISSUE THREAD

**Issue by ggsDing** [fyu/drn#36]
Traceback (most recent call last):
  File "segment.py", line 743, in <module>
    main()
  File "segment.py", line 735, in main
    args = parse_args()
  File "segment.py", line 729, in parse_args
    drn.BatchNorm = batchnormsync.BatchNormSync
NameError: name 'batchnormsync' is not defined

**Comment by Morgan-117** [comment]
you can add the lib dir to PYTHONPATH, for example:
export PYTHONPATH=$PYTHONPATH:`.../drn-master/lib`
