### ISSUE TITLE
tarfile.ReadError: invalid header

### ISSUE THREAD

**Issue by otas8070** [fyu/drn#7]
Hi.
I tried test, but this error was returned.
drn_d_22_cityscapes.pth is broken?

Command
`python3 segment.py test -d cityscapes/ -c 19 --arch drn_d_22 --pretrained drn_d_22_cityscapes.pth --phase test --batch-size 1`

Error
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/tarfile.py", line 182, in nti
    n = int(s.strip() or "0", 8)
ValueError: invalid literal for int() with base 8: 'ons\nOrde'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/tarfile.py", line 2281, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/local/lib/python3.5/tarfile.py", line 1083, in fromtarfile
    obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
  File "/usr/local/lib/python3.5/tarfile.py", line 1025, in frombuf
    chksum = nti(buf[148:156])
  File "/usr/local/lib/python3.5/tarfile.py", line 184, in nti
    raise InvalidHeaderError("invalid header")
tarfile.InvalidHeaderError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "segment.py", line 553, in <module>
    main()
  File "segment.py", line 550, in main
    test_seg(args)
  File "segment.py", line 467, in test_seg
    single_model.load_state_dict(torch.load(args.pretrained))
  File "/usr/local/lib/python3.5/site-packages/torch/serialization.py", line 248, in load
    return _load(f, map_location, pickle_module)
  File "/usr/local/lib/python3.5/site-packages/torch/serialization.py", line 314, in _load
    with closing(tarfile.open(fileobj=f, mode='r:', format=tarfile.PAX_FORMAT)) as tar, \
  File "/usr/local/lib/python3.5/tarfile.py", line 1577, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/local/lib/python3.5/tarfile.py", line 1607, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/usr/local/lib/python3.5/tarfile.py", line 1470, in __init__
    self.firstmember = self.next()
  File "/usr/local/lib/python3.5/tarfile.py", line 2293, in next
    raise ReadError(str(e))
tarfile.ReadError: invalid header
```

**Comment by fyu** [comment]
It is not broken. Please check your pytorch version.

**Comment by otas8070** [comment]
thanks!

**Comment by Gulshank04** [comment]
I am getting same issue as above, how to resolve this issue?
@otas8070 please guide
